name: 'unit_tests'

on:
  push:
    branches:
      - doom/2887_actions_units
  pull_request:

env:
  TARGETS: f7
  DEFAULT_TARGET: f7

jobs:
  main:
    runs-on: [self-hosted, FlipperZeroTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Get flipper from device manager (mock)'
        id: device
        run: |
          echo "flipper=/dev/ttyACM0" >> $GITHUB_OUTPUT

      - name: 'Compile unit tests firmware'
        id: compile
        continue-on-error: true
        run: |
          FBT_TOOLCHAIN_PATH=/opt ./fbt FIRMWARE_APP_SET=unit_tests flash_usb FORCE=1

      - name: 'Wait for flipper to finish updating'
        id: connect
        if: steps.compile.outcome == 'success'
        continue-on-error: true
        run: |
          ./scripts/testing/await_flipper.py ${{steps.device.outputs.flipper}}

      - name: 'Copy unit tests to flipper'
        id: copy
        if: steps.connect.outcome == 'success'
        continue-on-error: true
        run: |
          ./scripts/storage.py -p ${{steps.device.outputs.flipper}} send assets/unit_tests /ext/unit_tests

      - name: 'Run units and validate results'
        if: steps.copy.outcome == 'success'
        continue-on-error: true
        run: |
          ./scripts/testing/units.py ${{steps.device.outputs.flipper}}
