name: 'unit_tests'

on:
  push:
    branches:
      - doom/2887_actions_units
  pull_request:

env:
  TARGETS: f7
  DEFAULT_TARGET: f7

jobs:
  main:
    runs-on: [self-hosted, FlipperZeroTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Compile unit tests firmware'
        id: compile
        continue-on-error: true
        run: |
          FBT_TOOLCHAIN_PATH=/opt ./fbt FIRMWARE_APP_SET=unit_tests flash_usb FORCE=1

      - name: 'Wait for flipper to finish updating'
        id: connect
        if: steps.compile.outcome == 'success'
        continue-on-error: true
        run: |
          cd /home/actions-runner/actions-runner/QA-flipper-units
          /home/actions-runner/.local/bin/poetry run python3 /home/actions-runner/actions-runner/QA-flipper-units/check_flipper_availability.py /dev/ttyACM0

      - name: 'Copy unit tests to flipper'
        id: copy
        if: steps.connect.outcome == 'success'
        continue-on-error: true
        run: |
          ./scripts/storage.py -p /dev/ttyACM0 send assets/unit_tests /ext/unit_tests

      - name: 'Run units and validate results'
        if: steps.copy.outcome == 'success'
        continue-on-error: true
        run: |
          cd /home/actions-runner/actions-runner/QA-flipper-units
          /home/actions-runner/.local/bin/poetry run python3 run_units.py /dev/ttyACM0
